[build]

  publish = ".next"
  command = "npm run build"
  environment = { NODE_VERSION = "18.15.0" }

[build.development]
  environment = { NEXT_PUBLIC_BRANCH = 'development' }

[build.production]
  environment = { NEXT_PUBLIC_BRANCH = 'main' }