backend:
  name: git-gateway
  branch: development

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
logo_url: "https://amends.netlify.com/img/frequency-black.png"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "site/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    summary: "{{title}} ─ {{month}}/{{day}}/{{year}}"
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - label: "Weekly / Monthly Summary Post?"
        name: "category"
        widget: "select"
        hint: "Select a category to categorize this post as a weekly or monthly summary"
        required: false
        options: 
          - { label: "Weekly Summary", value: "weekly_summary" }
          - { label: "Monthly Summary", value: "monthly_summary" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Banner Image", name: "banner_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - label: "Latest Finds"
            name: "latest_finds"
            required: false
            widget: list
            fields: 
              - label: "Entry"
                name: "entry"
                widget: object
                fields:
                  - { label: "Title", name: "title", widget: string }
                  - { label: "Artist", name: "artist", widget: string }
                  - { label: "Album", name: "album", widget: string }
                  - { label: "Year", name: "year", widget: string }
                  - label: links
                    name: links
                    widget: list
                    fields: 
                      - label: Type
                        name: type
                        widget: select
                        options: 
                          - { label: Spotify, value: spotify }
                          - { label: Youtube, value: youtube }
                          - { label: Soundcloud, value: soundcloud }
                          - { label: Bandcamp, value: bandcamp }
                      - { label: Link, name: link, widget: string }
          # - {label: Message, name: message, widget: markdown, required: false}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Body, name: body, widget: markdown, required: false}
  - name: "globals"
    label: "Globals"
    editor:
      preview: false
    files: 
      - file: "site/content/globals/_index.md"
        name: "globals"
        label: "Globals"
        fields:
          - { label: Site Name, name: site_name, widget: string }
          - { label: Slogan, name: slogan, widget: string }
          - { label: Favicon, name: favicon, widget: image }
          - label: Branding
            name: branding
            widget: object
            fields:
              - label: Whites
                name: whites
                widget: object
                hint: "For dark backgrounds."
                fields: 
                  - { label: Icon, name: icon, widget: image }
                  - { label: Logo, name: logo, widget: image }
              - label: Blacks
                name: blacks
                widget: object
                hint: "For light backgrounds."
                fields: 
                  - { label: Icon, name: icon, widget: image }
                  - { label: Logo, name: logo, widget: image }
                
